### ISSUE TITLE
Does config=tsconfig.replace.json work?

### ISSUE THREAD

**Issue by clehene** [joseluisq/go-tspath#7]
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "allowJs": true,
    "outDir": "./dist",
    "skipLibCheck": true,
    "baseUrl":"./src",
    "paths": {
      "common/*": ["../../common/src/*"]
    }
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "src/**/*"
  ]
}
```

```
const logger_1 = require("common/logger");
```
becomes 
```
const logger_1 = require("./../../logger");
```

Actual code layout is 

```
dist
├── common
│   └── src
│       ├── logger.js
├── server
│   └── src
│       ├── csp.js
```

lastly config seems always ignored  

```
go-tspath -config=./tsconfig.replace.json
```
will produce the same output regardless of the config

**Comment by joseluisq** [comment]
The reason is because `go-tspath` is only supporting TS `paths` relative to `outDir` (not `baseUrl`) that's why your expected replacements are wrong.

`baseUrl` is only needed for TSC it means `.ts` source files not js transpiled files.

For example:

https://github.com/joseluisq/go-tspath/blob/eb4fa12860fa3f3b2647915a699f2b801d69f0dc/cmd/cmd.go#L25-L26

then the replacement loop process

https://github.com/joseluisq/go-tspath/blob/eb4fa12860fa3f3b2647915a699f2b801d69f0dc/cmd/cmd.go#L92-L102

And finally the replacement of bytes

https://github.com/joseluisq/go-tspath/blob/eb4fa12860fa3f3b2647915a699f2b801d69f0dc/pkg/replacer/replacer.go#L73-L80

Note `pathRel` is relative to `outDir`.

It would be great if I could see a more concrete project example with your configs.

**Comment by joseluisq** [comment]
Here I share with you my project setup working.

![image](https://user-images.githubusercontent.com/1700322/66028559-ac4b8500-e4fd-11e9-976d-bc060d1d3f1f.png)

All the js files are inside `./dist` and the `tsconfig.replace.json` in the root of the project.
It was transpiled via `tsc` using following config: 

```json
{
  "compilerOptions": {
    "outDir": "./dist",
    "strict": true,
    "pretty": false,
    "sourceMap": false,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": false,
    "experimentalDecorators": false,
    "allowSyntheticDefaultImports": true,
    "module": "commonjs",
    "target": "es6"
  }
}
```

Files marked in yellow were property replaced.

**Comment by clehene** [comment]
@joseluisq thank you for the detailed explanation!

I'm using `common` as a shared library across multiple "modules" (independent compilation units like React apps).
so the overall structure is
* app1
  * src
* app2
  * src
* common
  * src

Then I do tsconfig paths and associated webpack aliases for `common`.
I accidentally thought (due to a problem in Dokerfile) that `tsconfig-paths/register` doesn't work, which is how I got to your project.

Feel free to close it if you think there's nothing to be fixed :)

**Comment by joseluisq** [comment]
I understand.
`go-tspath` was conceived to solve a common use case. But I would be interesting to test it with other use cases as yours. That's for sure. Which would derive into useful feedback to this tool too.

I think about your use case as an enhancement for this tool.
So, feel free to contribute or open this issue again if it's needed.
